/**
 * Interface for representing the internally used user object.
 */
export interface User {
    /**
     * Id of the user. Generated by the server.
     */
    id?: string;
    /**
     * The name of the user, set via registration.
     */
    name: string;
}
